zuul:
  routes:
    fake-service:
      path: /fake-service/**
      serviceId: fake-service
management:
  security:
    enabled: false
debug: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/
spring:
  application:
    name: zuul-api-gateway
zuul:
  ratelimit:
    enabled: true
    behind-proxy: true
    default-policy: #optional - will apply unless specific policy exists
      limit: 3 #optional - request number limit per refresh interval window
      quota: 1000 #optional - request time limit per refresh interval window (in seconds)
      refresh-interval: 60 #default value (in seconds)
      type: #optional
        - user
        - origin
        - url