zuul:
  routes:
    rs-service:
      path: /api-gateway/rs-service/**
#      url: http://buchunzaide.com
    sample-service:
      path: /too-young-too-sample
      url: localhost:8082/echo/test2
#    sieble-service:
#      path: /api-gateway/rs-service/sieble/**
#      serviceId: fake-service
management:
  security:
    enabled: false
debug: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/
spring:
  application:
    name: zuul-api-gateway
